---
strategy: polling
no_screen_padding: 'yes'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://naolib-worker.YOUR_SUBDOMAIN.workers.dev/?lat=YOUR_LAT&lng=YOUR_LNG
polling_headers: ''
polling_body: ''
name: Naolib Departures
refresh_interval: 60
