---
strategy: polling
no_screen_padding: 'yes'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://open.tan.fr/ewp/arrets.json/47,21661/-1,556754
polling_headers: ''
polling_body: ''
name: Naolib Departures
refresh_interval: 60
